import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useState, useEffect } from "react";

const Home: NextPage = () => {
  const [items, setItems] = useState([]);
  useEffect(() => {
    const getItems = () => {
      fetch("https://fakestoreapi.com/products")
        .then((res) => res.json())
        .then((json) => setItems(json));
    };
    getItems();
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        <h2 className="text-[3rem] lg:text-[5rem] md:text-[5rem] font-extrabold text-gray-700">
          Create <span className="text-purple-300">T3</span> App
        </h2>
        <p className="text-2xl text-gray-700">This stack uses</p>
        <div className="grid grid-cols-1 grid-rows-3 lg:grid-rows-2 md:grid-rows-2 justify-center items-center lg:grid-cols-2 md:grid-cols-2 gap-3 mt-3 pt-3 w-full lg:w-2/3 md:w-full">
          {items?.map((item) => (
            <div className="hover:scale-105 cursor-pointer duration-500 flex flex-col justify-center items-center text-center rounded shadow-xl border-2 border-gray-500 h-full w-full p-6">
              {item.title}
              <img src={item.image} alt={item.title} />
              {item.price}
            </div>
          ))}
          <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full"></div>
        </div>
      </div>
    </>
  );
};

export default Home;
